trigger: none

pool:
  name: windows-latest

workspace:
  clean: all

steps:
- checkout: self

- task: TerraformInstaller@0
  displayName: Install Terraform
  inputs:
    terraformVersion: '0.12.29'

- task: TerraformTaskV1@0
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    environmentServiceNameAzureRM: 'Service-Connection' #Service connection created in AzureDevops
    workingDirectory: '$(System.DefaultWorkingDirectory)/MacroLife'
    backendServiceArm: 'Service-Connection' #Service connection created in AzureDevops
    backendAzureRmResourceGroupName: 'terraform-resource-group' #resource group create to store below mentionde storage account pertaining
    backendAzureRmStorageAccountName: 'terraform-storage-account' #storage account that will store tF state files
    backendAzureRmContainerName: 'tfstatefiles' 
    backendAzureRmKey: '{Environment}.terraform.tfstate' #Environment could be dev/test/QA/PROD that's supplied at build time.

- task: TerraformTaskV1@0
  displayName: Terraform Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/MacroLife'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'Service-Connection' #Service connection created in AzureDevops
...
