variable "location" {}
variable "name" {}
variable "env" {}
variable "account_replication_type" {}
variable "account_tier" {}
variable "account_kind" {}
variable "resource_group_name" {}
variable "ip_rules" {}
variable "virtual_network_subnet_ids" {}
